### ISSUE TITLE
Issue with GitHub stats

### ISSUE THREAD

**Issue by AvidCoder101** [gbgabiola/gbgabiola#1]
The GitHub statistics are unavailable : 

![image](https://user-images.githubusercontent.com/70807684/126072404-34b1b67b-7ee1-4702-adf8-6eb876ed45bf.png)

**Comment by gbgabiola** [comment]
> The GitHub statistics are unavailable :
> 
> ![image](https://user-images.githubusercontent.com/70807684/126072404-34b1b67b-7ee1-4702-adf8-6eb876ed45bf.png)

**Comment by gbgabiola** [comment]
Thanks for letting me know, I'll be fixing it later.
